const Menu = [
  {
    id: 1,
    image: "/assets/images/bristore/1.svg",
    writer: "By Ahana Gangul",
    bookname: "Apocalypse 1",
    price: "170.00",
    category: "Toddlers",
  },
  {
    id: 2,
    image: "/assets/images/bristore/2.svg",
    writer: "By Nysa Gar",
    bookname: "The Secrets of the Realms 2",
    price: "99.00",
    category: "Toddlers",
  },
  {
    id: 3,
    image: "/assets/images/bristore/3.svg",
    writer: "By Abhay Srivastav",
    bookname: "How to Write Nicely 3",
    price: "120.00",
    category: "Toddlers",
  },
  {
    id: 4,
    image: "/assets/images/bristore/4.svg",
    writer: "By Avni Sara",
    bookname: "Oceans of the world 4",
    price: "80.00",
    category: "Toddlers",
  },
  {
    id: 5,
    image: "/assets/images/bristore/5.svg",
    writer: "By Sanvi Pund",
    bookname: "Fantastic poems-6 in 1",
    price: "145.00",
    category: "Pre-School",
  },
  {
    id: 6,
    image: "/assets/images/bristore/4.svg",
    writer: "By Thiruvarma",
    bookname: "Harry’s Birthday 2",
    price: "96.00",
    category: "Pre-School",
  },
  {
    id: 7,
    image: "/assets/images/bristore/3.svg",
    writer: "By Abhay Srivastav",
    bookname: "How to Write Nicely 3",
    price: "120.00",
    category: "Pre-School",
  },
  {
    id: 8,
    image: "/assets/images/bristore/4.svg",
    writer: "By Avni Sara",
    bookname: "Oceans of the world 4",
    price: "80.00",
    category: "Pre-School",
  },
  {
    id: 9,
    image: "/assets/images/bristore/5.svg",
    writer: "By Sanvi Pund",
    bookname: "Fantastic poems-6 in 1",
    price: "145.00",
    category: "Primary School",
  },
  {
    id: 10,
    image: "/assets/images/bristore/4.svg",
    writer: "By Thiruvarma",
    bookname: "Harry’s Birthday 2",
    price: "96.00",
    category: "Primary School",
  },
  {
    id: 11,
    image: "/assets/images/bristore/1.svg",
    writer: "By Ahana Gangul",
    bookname: "Apocalypse 3",
    price: "170.00",
    category: "Primary School",
  },
  {
    id: 12,
    image: "/assets/images/bristore/2.svg",
    writer: "By Nysa Gar ",
    bookname: "The Secrets of the Realms 1",
    price: "99.00",
    category: "9th Grade",
  },
  {
    id: 13,
    image: "/assets/images/bristore/3.svg",
    writer: "By Abhay Srivastav",
    bookname: "How to Write Nicely 2 ",
    price: "120.00",
    category: "9th Grade",
  },
  {
    id: 14,
    image: "/assets/images/bristore/4.svg",
    writer: "By Avni Sara",
    bookname: "Oceans of the world 3",
    price: "80.00",
    category: "9th Grade",
  },
  {
    id: 15,
    image: "/assets/images/bristore/5.svg",
    writer: "By Sanvi Pund",
    bookname: "Fantastic poems-6 in 1",
    price: "145.00",
    category: "10th Grade",
  },
  {
    id: 16,
    image: "/assets/images/bristore/4.svg",
    writer: "By Thiruvarma",
    bookname: "Harry’s Birthday 2",
    price: "96.00",
    category: "10th Grade",
  },
  {
    id: 17,
    image: "/assets/images/bristore/3.svg",
    writer: "By Abhay Srivastav",
    bookname: "How to Write Nicely 3",
    price: "120.00",
    category: "10th Grade",
  },
  {
    id: 18,
    image: "/assets/images/bristore/4.svg",
    writer: "By Avni Sara",
    bookname: "Oceans of the world 1",
    price: "80.00",
    category: "11th Grade",
  },
  {
    id: 19,
    image: "/assets/images/bristore/5.svg",
    writer: "By Sanvi Pund",
    bookname: "Fantastic poems-6 in 2",
    price: "145.00",
    category: "11th Grade",
  },
  {
    id: 20,
    image: "/assets/images/bristore/4.svg",
    writer: "By Thiruvarma",
    bookname: "Harry’s Birthday 3",
    price: "96.00",
    category: "11th Grade",
  },
  {
    id: 21,
    image: "/assets/images/bristore/4.svg",
    writer: "By Thiruvarma",
    bookname: "Harry’s Birthday 4",
    price: "96.00",
    category: "11th Grade",
  },
  {
    id: 22,
    image: "/assets/images/bristore/4.svg",
    writer: "By Thiruvarma",
    bookname: "Harry’s Birthday 1",
    price: "96.00",
    category: "12th Grade",
  },
  {
    id: 23,
    image: "/assets/images/bristore/4.svg",
    writer: "By Thiruvarma",
    bookname: "Harry’s Birthday 2",
    price: "96.00",
    category: "12th Grade",
  },
  {
    id: 24,
    image: "/assets/images/bristore/4.svg",
    writer: "By Thiruvarma",
    bookname: "Harry’s Birthday 3",
    price: "96.00",
    category: "12th Grade",
  },
  {
    id: 25,
    image: "/assets/images/bristore/4.svg",
    writer: "By Thiruvarma",
    bookname: "Harry’s Birthday 4",
    price: "96.00",
    category: "12th Grade",
  },
];
export default Menu;
